### ISSUE TITLE
Text change Import BW

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6755]
Import : Text should be ”Border wallet imported successfully”

![img_9659_720](https://github.com/bithyve/bitcointribe/assets/107177634/43051828-0e1d-45f8-866b-0bb8a4eea458)

**Comment by akshay8551** [comment]
Done,

![Simulator Screen Shot - iPhone 14 - 2023-09-18 at 11 01 56](https://github.com/bithyve/bitcointribe/assets/61345820/f255fb1f-5c84-4935-aa8e-f708b9a7543e)


![Simulator Screen Shot - iPhone 14 - 2023-09-18 at 11 03 39](https://github.com/bithyve/bitcointribe/assets/61345820/d2d5e3f1-40f2-431c-b773-ec03ea1e130a)

**Comment by cakesoft-swati** [comment]
- It is still showing created message instead of import.

Uploading Record_2023-09-27-15-25-35.mp4…

**Comment by Deveshshankar** [comment]
Need to check
